import { Activity, Archive, Bell, Bot, Box, Boxes, Brain, Bug, Calendar, Camera, Captions, Cctv, ChartLine, Clapperboard, Cloud, Code, Cog, Cpu, Database, Download, FileText, Film, FolderOpen, Gamepad2, Gauge, Globe, HardDrive, Headphones, HeartPulse, Home, House, Image, Key, Layers, LayoutDashboard, Lightbulb, Lock, Mail, Map, MessagesSquare, Mic, Monitor, Music, Network, Package, Play, PlayCircle, Power, Printer, Radar, Radio, Router, Search, Server, Settings, Share2, Shield, ShieldCheck, Smartphone, Terminal, Thermometer, Ticket, Tv, Upload, Video, Wifi, Wrench, Zap, type LucideIcon } from "lucide-react"

/**
 * Icons selectable as `lucide:<name>` for an app. Kept as a curated static list so the
 * bundle stays small; extend it freely, names are kebab-case.
 */
export const LUCIDE_ICONS: Record<string, LucideIcon> = { "activity": Activity, "archive": Archive, "bell": Bell, "bot": Bot, "box": Box, "boxes": Boxes, "brain": Brain, "bug": Bug, "calendar": Calendar, "camera": Camera, "captions": Captions, "cctv": Cctv, "chart-line": ChartLine, "clapperboard": Clapperboard, "cloud": Cloud, "code": Code, "cog": Cog, "cpu": Cpu, "database": Database, "download": Download, "file-text": FileText, "film": Film, "folder-open": FolderOpen, "gamepad2": Gamepad2, "gauge": Gauge, "globe": Globe, "hard-drive": HardDrive, "headphones": Headphones, "heart-pulse": HeartPulse, "home": Home, "house": House, "image": Image, "key": Key, "layers": Layers, "layout-dashboard": LayoutDashboard, "lightbulb": Lightbulb, "lock": Lock, "mail": Mail, "map": Map, "messages-square": MessagesSquare, "mic": Mic, "monitor": Monitor, "music": Music, "network": Network, "package": Package, "play": Play, "play-circle": PlayCircle, "power": Power, "printer": Printer, "radar": Radar, "radio": Radio, "router": Router, "search": Search, "server": Server, "settings": Settings, "share2": Share2, "shield": Shield, "shield-check": ShieldCheck, "smartphone": Smartphone, "terminal": Terminal, "thermometer": Thermometer, "ticket": Ticket, "tv": Tv, "upload": Upload, "video": Video, "wifi": Wifi, "wrench": Wrench, "zap": Zap }

export const LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICONS)
